name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20    # Changed from 18 to 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
          
      - name: Build with Next.js
        env:
            NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
        run: npm run build

      - name: Debug Environment Variables
        run: |
          if [ -n "$NEXT_PUBLIC_GEMINI_API_KEY" ]; then
            echo " NEXT_PUBLIC_GEMINI_API_KEY is set and not empty"
          else
            echo " NEXT_PUBLIC_GEMINI_API_KEY is empty or not set"
            exit 1
          fi
        env:
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4